check_every_seconds_default: 5
log_level: DEBUG

kafka_connect:
  uri: 'kafka-1b5de807-kost-8b9f.aivencloud.com:12887'
  topic: 'website-monitor'
  cafile: ca.pem
  certfile: service.cert
  keyfile: service.key

websites:
  - url: https://www.google.com
    patterns:
      - '.*Google.*'

  - url: https://www.amazon.com

  - url: https://aiven.io
    patterns:
      - '.*Get Started.*'
      - '.*Performant data pipelines in minutes.*'

target:
  postgres_uri: 'postgres://avnadmin:vb3vymj1qlbk8rw6@pg-2aa26d62-kost-8b9f.aivencloud.com:12885/defaultdb?sslmode=require'
